### PR TITLE
Delete Tag 'launched-for-asg' when detaching a spot instance

### LINKED ISSUE #327: Terminating detached spot instance used to replace on demand one
# Github issue #

## Issue type ##

- Bug Report

## Build number #

master

## Environment ##

- AWS region
- Type of environment: (VPC, EC2Classic or DefaultVPC)
- Anonymized launch configuration: 

```text
```

## Summary ##

Following a spot termination notification, a previously launched spot instance has been detached from ASG, without decrementing ASG desired capacity so that ASG launch a new instance.

Happen that the new instance is launched in the same AZ that the spot terminating one.
Happen that before detached terminating spot instance terminate (so before 2 minutes), AutoSpotting is executed by scheduled event.

AutoSpotting (AS) look for spot instance ready do attach.
AS find the terminating spot instance:
it have the right tag "launched-for-asg" that match the ASG name and is state is still running.
AS find the ondeman one with the same AZ.
AS replace the ondemand instance with a nearly termination one!!!

AS and ASG log/events.
```
AS 2019-02-20T07:01:54.789Z 2019/02/20 07:01:54 Detached instance i-02a941d2d30a40a3c successfully
ASG At 2019-02-20T07:01:54Z instance i-02a941d2d30a40a3c was detached in response to a user request.
ASG At 2019-02-20T07:02:19Z Launching a new EC2 instance: i-095878a259a6c9e2b - an instance was started in response to a difference between desired and actual capacity, increasing the capacity from 0 to 1.
AS 2019/02/20 07:02:32 autoscaling.go:442: rmq-a-d-AutoScalingGroup-1HSLJRZ51V8Q7 found on-demand instance i-095878a259a6c9e2b replacing with new spot instance i-02a941d2d30a40a3c
```

## Steps to reproduce ##

Create ASG with desired=min=max=1
Wait until AS replace the ondemand with a spot one.
One minute before next AS execution, pubblish the following message on sns spot termination notification Topic (replacing spot-instance-id with the right one):
```
{
  "detail": {
    "instance-id": "spot-instance-id",
    "instance-action": "terminate"
  }
}

```
Look for AS log and ASG events.
If the new ondemand instance is launched in the same AZ, the events previously described should happen. 

## Expected results ##

AutoSpotting should not use a terminating previously launched spot instance to replace an on demand one.

## Actual results ##

AutoSpotting have used a terminating previously launched spot instance to replace an on demand one.

## Possible Fix ##
I am working to add the option to choose between detaching or terminating a spot instance when a spot notification message is received.
Terminating it had the advantage of triggering lifecyclehook and to avoid this problem.
But if we want to keep detach as possible action we need to fix this.

One way should be to remove the tag "launched-for-asg" after attaching a spot instance successfully to an ASG.

### PR DESCRIPTION
**Pull request by mello7tre**
# Issue Type

- Bugfix Pull Request

## Summary

In some situation (described in detail in #327), a detaching near termination
spot instance can be used to replace an ondemand one.

This fix delete the Tag 'launched-for-asg' after successfully detaching
a spot instance.

Fixes #327

## Code contribution checklist

1. [X] The contribution fixes a single existing github issue, and it is linked
   to it.
1. [ ] The code is as simple as possible, readable and follows the idiomatic Go
  [guidelines](https://golang.org/doc/effective_go.html).
1. [X] All new functionality is covered by automated test cases so the overall
  test coverage doesn't decrease.
1. [ ] No issues are reported when running `make full-test`.
1. [ ] Functionality not applicable to all users should be configurable.
1. [ ] Configurations should be exposed through Lambda function environment
   variables which are also passed as parameters to the
   [CloudFormation](https://github.com/cristim/autospotting/blob/master/cloudformation/stacks/AutoSpotting/template.yaml)
   and
   [Terraform](https://github.com/autospotting/terraform-aws-autospotting/main.tf)
   stacks defined as infrastructure code.
1. [ ] Global configurations set from the infrastructure stack level should also
   support per-group overrides using tags.
1. [ ] Tags names and expected values should be similar to the other existing
   configurations.
1. [ ] Both global and tag-based configuration mechanisms should be tested and
  proven to work using log output from various test runs.
1. [ ] The logs should be kept as clean as possible (use log levels as
  appropriate) and formatted consistently to the existing log output.
1. [ ] The documentation is updated to cover the new behavior, as well as the
   new configuration options for both stack parameters and tag overrides.
1. [ ] A code reviewer reproduced the problem and can confirm the code
  contribution actually resolves it.

### CODE REVIEW

File: core/spot_termination.go [hunk 1]
```diff
@@ -147,6 +154,29 @@ func (s *SpotTermination) ExecuteAction(instanceID *string, terminationNotificat
...
+		},
+	}
+	_, err := s.ec2Svc.DeleteTags(&ec2Params)
+
+	if err != nil {
+		logger.Printf("Failed to delete Tag 'launched-for-asg' from spot instance %s with err: %s\n", *instanceID, err.Error())
+		return err
+	}
+
+	log.Printf("Tag 'launched-for-asg' delete from spot instance %s", *instanceID)
```
Comment (cristim) [inline core/spot_termination.go]: I would say delete**d** here
