### PR TITLE
Ignore terminating spot instances that don't belong to AutoSpotting

### LINKED ISSUE #362: Spot Instance Termination is Generic
# Github issue #

## Issue type ##
- Bug Report

## Build number #

master branch

## Summary ##

During Spot Instance termination, the function does not take into consideration the tags of the instance's AutoScaling group or will run into a conflict if multiple AutoSpotting functions are deployed. 

AutoScaling groups that do not use AutoSpotting are also affected, this can cause issues with tools such as https://github.com/pusher/k8s-spot-termination-handler

## Steps to reproduce ##
Trigger spot termination event

## Expected results ##
Spot termination event to only affect a subset of instances - those that are covered by AutoSpotting and have the correct tags

## Actual results ##
Any instance that has spot termination is affected

### PR DESCRIPTION
**Pull request by gabegorelick**
This is a reworking of #363 against `master`. 

Since this fixes a fairly serious issues for those running AutoSpotting in multi-tenant environments, I think it makes sense to merge this first and then tackle remaining issues that are preventing #354 from being merged. 

Credit for original code goes to @cfarrend.

Fixes #362
Closes #363
Closes #390

# Issue Type

- Bugfix Pull Request

## Code contribution checklist

1. [x] I hereby allow the Copyright holder the rights to distribute this piece of
   code under any software license.
1. [ ] The contribution fixes a single existing github issue, and it is linked
   to it.
1. [ ] The code is as simple as possible, readable and follows the idiomatic Go
  [guidelines](https://golang.org/doc/effective_go.html).
1. [ ] All new functionality is covered by automated test cases so the overall
  test coverage doesn't decrease.
1. [ ] No issues are reported when running `make full-test`.
1. [ ] Functionality not applicable to all users should be configurable.
1. [ ] Configurations should be exposed through Lambda function environment
   variables which are also passed as parameters to the
   [CloudFormation](https://github.com/cristim/autospotting/blob/master/cloudformation/stacks/AutoSpotting/template.yaml)
   and
   [Terraform](https://github.com/autospotting/terraform-aws-autospotting/main.tf)
   stacks defined as infrastructure code.
1. [ ] Global configurations set from the infrastructure stack level should also
   support per-group overrides using tags.
1. [ ] Tags names and expected values should be similar to the other existing
   configurations.
1. [ ] Both global and tag-based configuration mechanisms should be tested and
  proven to work using log output from various test runs.
1. [ ] The logs should be kept as clean as possible (use log levels as
  appropriate) and formatted consistently to the existing log output.
1. [ ] The documentation is updated to cover the new behavior, as well as the
   new configuration options for both stack parameters and tag overrides.
1. [ ] A code reviewer reproduced the problem and can confirm the code
  contribution actually resolves it.

### CODE REVIEW

File: autospotting.go [hunk 1]
```diff
@@ -137,7 +137,15 @@ func Handler(ctx context.Context, rawEvent json.RawMessage) {
 			return
 		} else if instanceID != nil {
 			spotTermination := autospotting.NewSpotTermination(cloudwatchEvent.Region)
-			spotTermination.ExecuteAction(instanceID, conf.TerminationNotificationAction)
+			if spotTermination.IsInAutoSpottingASG(instanceID, conf.TagFilteringMode, conf.FilterByTags) {
+				err := spotTermination.ExecuteAction(instanceID, conf.TerminationNotificationAction)
+				if err != nil {
```
[the remark this answers is not in the document]
Comment (gabegorelick) [reply autospotting.go]: Had to rewrite some of the this code to appease codeclimate, but it retains the spirit of @cfarrend's original PR.

File: core/spot_termination.go [hunk 2]
```diff
@@ -206,3 +210,51 @@ func (s *SpotTermination) asgHasTerminationLifecycleHook(autoScalingGroupName *s
...
+	for _, tagWithValue := range strings.Split(filters, ",") {
+		tag := splitTagAndValue(tagWithValue)
+		if tag != nil {
+			tagsToMatch = append(tagsToMatch, *tag)
+		}
+	}
+
+	isInASG := optInFilterMode == isASGWithMatchingTags(asgGroupsOutput.AutoScalingGroups[0], tagsToMatch)
+
+	if isInASG == false {
```
Comment (golangcibot) [inline core/spot_termination.go]: S1002: should omit comparison to bool constant, can be simplified to `!isInASG` (from `gosimple`)

Comment (gabegorelick) [reply core/spot_termination.go]: You can tell I'm still learning go :)

File: core/spot_termination.go [hunk 3]
```diff
@@ -121,13 +122,13 @@ func (s *SpotTermination) getAsgName(instanceID *string) (string, error) {
 	}
 
 	result, err := s.asSvc.DescribeAutoScalingInstances(&asParams)
-
-	var asgName = ""
-	if err == nil {
-		asgName = *result.AutoScalingInstances[0].AutoScalingGroupName
+	if err != nil {
+		return "", err
+	} else if len(result.AutoScalingInstances) == 0 {
```
Comment (gabegorelick) [inline core/spot_termination.go]: This is from #388. @cristim if you merge that first I can rebase this change away.

File: core/spot_termination.go [hunk 4]
```diff
@@ -206,3 +210,57 @@ func (s *SpotTermination) asgHasTerminationLifecycleHook(autoScalingGroupName *s
 
 	return hasHook
 }
+
+// IsInAutoSpottingASG checks to see whether an instance is in an AutoSpotting ASG as defined by its tags.
+// If the ASG does not have the required tags, it is not an AutoSpotting ASG and should be left alone.
+func (s *SpotTermination) IsInAutoSpottingASG(instanceID *string, tagFilteringMode string, filterByTags string) bool {
```
[the remark this answers is not in the document]
Comment (gabegorelick) [reply core/spot_termination.go]: Fixed

File: core/spot_termination.go (hunk 3 above)
Comment (gabegorelick) [reply core/spot_termination.go]: Rebased away.

**Comment by gabegorelick** [comment]
@cristim This should be ready to merge.

**Comment by cristim** [comment]
Thanks again for your contribution
