### PR TITLE
Move some logs to debug

### LINKED ISSUE #382: AutoSpotting logs too much by default
## Issue type ##

Feature Idea

## Build number #

master

## Summary ##

AutoSpotting logs a lot of information by default. While it's great to have such more info should something go wrong, in practice I think it often makes it harder to debug issues. In an environment with a lot of auto scaling groups, the amount of logs can be overwhelming and makes it difficult to get a sense of what AutoSpotting is actually doing.

Some of the logs that are arguably not worth including by default:
- `Processing page`
- `Skipping group`

These can still be logged at the debug level, but I don't think they're worth logging at the default level.

## Steps to reproduce ##

Run AutoSpotting in a region with lots of ASGs.

## Expected results ##

AutoSpotting logs only what's needed to investigate issues that could arise.

## Actual results ##

So much output that it's hard to follow. I count 444 lines in my environment on an invocation where AutoSpotting didn't even launch or terminate any instances.

### PR DESCRIPTION
**Pull request by gabegorelick**
I don't think these logs decrease the signal-to-noise ratio for everyday use, although others may disagree.

I'm happy to break this up into smaller PRs if that's desired, and I'm happy to remove anything from this PR that you think is worth keeping.

Fixes #382

# Issue Type

Feature Pull Request

## Summary

Move some logs to debug.

In my tests, I'm seeing lines logged go from > 500 to < 100 for invocations where AutoSpotting doesn't terminate or launch any instances. 

## Code contribution checklist

1. [x] I hereby allow the Copyright holder the rights to distribute this piece of
   code under any software license.
1. [ ] The contribution fixes a single existing github issue, and it is linked
   to it.
1. [ ] The code is as simple as possible, readable and follows the idiomatic Go
  [guidelines](https://golang.org/doc/effective_go.html).
1. [ ] All new functionality is covered by automated test cases so the overall
  test coverage doesn't decrease.
1. [ ] No issues are reported when running `make full-test`.
1. [ ] Functionality not applicable to all users should be configurable.
1. [ ] Configurations should be exposed through Lambda function environment
   variables which are also passed as parameters to the
   [CloudFormation](https://github.com/cristim/autospotting/blob/master/cloudformation/stacks/AutoSpotting/template.yaml)
   and
   [Terraform](https://github.com/autospotting/terraform-aws-autospotting/main.tf)
   stacks defined as infrastructure code.
1. [ ] Global configurations set from the infrastructure stack level should also
   support per-group overrides using tags.
1. [ ] Tags names and expected values should be similar to the other existing
   configurations.
1. [ ] Both global and tag-based configuration mechanisms should be tested and
  proven to work using log output from various test runs.
1. [ ] The logs should be kept as clean as possible (use log levels as
  appropriate) and formatted consistently to the existing log output.
1. [ ] The documentation is updated to cover the new behavior, as well as the
   new configuration options for both stack parameters and tag overrides.
1. [ ] A code reviewer reproduced the problem and can confirm the code
  contribution actually resolves it.

### CODE REVIEW

File: core/connections.go [hunk 1]
```diff
@@ -32,7 +32,7 @@ func (c *connections) setSession(region string) {
 
 func (c *connections) connect(region string) {
 
-	logger.Println("Creating Service connections in", region)
+	debug.Println("Creating service connections in", region)
```
Comment (gabegorelick) [inline core/connections.go]: Before:

```
2020/01/25 17:22:00 main.go:129: Scanning for available AWS regions
2020/01/25 17:22:01 main.go:101: Enabled to run in us-east-1, processing region.
2020/01/25 17:22:01 region.go:78: Creating connections to the required AWS services in us-east-1
2020/01/25 17:22:01 connections.go:35: Creating Service connections in us-east-1
2020/01/25 17:22:01 connections.go:51: Created service connections in us-east-1
2020/01/25 17:22:01 region.go:85: Scanning for enabled AutoScaling groups in  us-east-1
```

The above is repeated per region, so it adds up if running in a lot of regions.


After:
```
020/01/25 17:26:56 main.go:129: Scanning for available AWS regions
2020/01/25 17:26:56 main.go:101: Enabled to run in us-west-2, processing region.
2020/01/25 17:26:56 region.go:78: Creating connections to the required AWS services in us-west-2
2020/01/25 17:26:56 connections.go:35: Creating Service connections in us-west-2
2020/01/25 17:26:56 main.go:101: Enabled to run in sa-east-1, processing region.
2020/01/25 17:26:56 region.go:78: Creating connections to the required AWS services in sa-east-1
2020/01/25 17:26:56 connections.go:35: Creating Service connections in sa-east-1
```

Since we still have the `Enabled to run in us-west-2, processing region` log, I don't think much is missed by removing these.

File: core/region.go [hunk 2]
```diff
@@ -271,13 +271,13 @@ func (r *region) requestSpotPrices() error {
 		// spot market
 		price, err := strconv.ParseFloat(*priceInfo.SpotPrice, 64)
 		if err != nil {
-			logger.Println(r.name, "Instance type ", instType,
+			debug.Println(r.name, "Instance type ", instType,
```
Comment (gabegorelick) [inline core/region.go]: I think it's enough to log the resources that AutoSpotting *is* processing and omit logs for everything it's not.

File: core/region.go [hunk 3]
```diff
@@ -377,14 +377,14 @@ func (r *region) findMatchingASGsInPageOfResults(groups []*autoscaling.Group,
...
-			logger.Printf("Skipping group %s because its tags, the currently "+
+			debug.Printf("Skipping group %s because its tags, the currently "+
 				"configured filtering mode (%s) and tag filters do not align\n",
 				asgName, r.conf.TagFilteringMode)
 			continue
 		}
 
 		if stackName := getTagValueFromASGWithMatchingTag(group, tagCloudFormationStackName); stackName != nil {
-			logger.Println("Stack: ", *stackName)
+			debug.Println("Stack: ", *stackName)
```
Comment (gabegorelick) [inline core/region.go]: We log if the stack is updating. If it's not updating, the stack isn't that interesting.

File: core/region.go [hunk 4]
```diff
@@ -271,13 +271,13 @@ func (r *region) requestSpotPrices() error {
...
 		if err != nil {
-			logger.Println(r.name, "Instance type ", instType,
+			debug.Println(r.name, "Instance type ", instType,
 				"is not available on the spot market")
 			continue
 		}
 
 		if r.instanceTypeInformation[instType].pricing.spot == nil {
-			logger.Println(r.name, "Instance data missing for", instType, "in", az,
+			debug.Println(r.name, "Instance data missing for", instType, "in", az,
```
Comment (gabegorelick) [inline core/region.go]: Removes this wall of text from every invocation:
```
2020/01/25 17:32:07 region.go:280: us-east-1 Instance data missing for g4dn.2xlarge in us-east-1f skipping because this region is currently not supported
2020/01/25 17:32:07 region.go:280: us-east-1 Instance data missing for g4dn.xlarge in us-east-1a skipping because this region is currently not supported
2020/01/25 17:32:07 region.go:280: us-east-1 Instance data missing for g4dn.16xlarge in us-east-1b skipping because this region is currently not supported
2020/01/25 17:32:07 region.go:280: us-east-1 Instance data missing for g4dn.16xlarge in us-east-1f skipping because this region is currently not supported
2020/01/25 17:32:07 region.go:280: us-east-1 Instance data missing for g4dn.16xlarge in us-east-1a skipping because this region is currently not supported
2020/01/25 17:32:07 region.go:280: us-east-1 Instance data missing for g4dn.16xlarge in us-east-1d skipping because this region is currently not supported
2020/01/25 17:32:07 region.go:280: us-east-1 Instance data missing for g4dn.16xlarge in us-east-1c skipping because this region is currently not supported
2020/01/25 17:32:07 region.go:280: us-east-1 Instance data missing for m5n.large in us-east-1b skipping because this region is currently not supported
2020/01/25 17:32:07 region.go:280: us-east-1 Instance data missing for m5n.large in us-east-1f skipping because this region is currently not supported
2020/01/25 17:32:07 region.go:280: us-east-1 Instance data missing for m5n.large in us-east-1a skipping because this region is currently not supported
2020/01/25 17:32:07 region.go:280: us-east-1 Instance data missing for m5n.large in us-east-1d skipping because this region is currently not supported
2020/01/25 17:32:07 region.go:280: us-east-1 Instance data missing for m5n.large in us-east-1c skipping because this region is currently not supported
2020/01/25 17:32:07 region.go:280: us-east-1 Instance data missing for a1.metal in us-east-1a skipping because this region is currently not supported
2020/01/25 17:32:07 region.go:280: us-east-1 Instance data missing for m5dn.24xlarge in us-east-1b skipping because this region is currently not supported
2020/01/25 17:32:07 region.go:280: us-east-1 Instance data missing for m5dn.24xlarge in us-east-1f skipping because this region is currently not supported
2020/01/25 17:32:07 region.go:280: us-east-1 Instance data missing for m5dn.24xlarge in us-east-1a skipping because this region is currently not supported
2020/01/25 17:32:07 region.go:280: us-east-1 Instance data missing for m5dn.24xlarge in us-east-1d skipping because this region is currently not supported
2020/01/25 17:32:07 region.go:280: us-east-1 Instance data missing for m5dn.24xlarge in us-east-1c skipping because this region is currently not supported
2020/01/25 17:32:07 region.go:280: us-east-1 Instance data missing for inf1.6xlarge in us-east-1f skipping because this region is currently not supported
2020/01/25 17:32:07 region.go:280: us-east-1 Instance data missing for inf1.6xlarge in us-east-1a skipping because this region is currently not supported
2020/01/25 17:32:07 region.go:280: us-east-1 Instance data missing for inf1.6xlarge in us-east-1d skipping because this region is currently not supported
2020/01/25 17:32:07 region.go:280: us-east-1 Instance data missing for c5n.metal in us-east-1b skipping because this region is currently not supported
2020/01/25 17:32:07 region.go:280: us-east-1 Instance data missing for c5n.metal in us-east-1f skipping because this region is currently not supported
2020/01/25 17:32:07 region.go:280: us-east-1 Instance data missing for c5n.metal in us-east-1a skipping because this region is currently not supported
2020/01/25 17:32:07 region.go:280: us-east-1 Instance data missing for c5n.metal in us-east-1d skipping because this region is currently not supported
2020/01/25 17:32:07 region.go:280: us-east-1 Instance data missing for c5n.metal in us-east-1c skipping because this region is currently not supported
2020/01/25 17:32:07 region.go:280: us-east-1 Instance data missing for m5n.4xlarge in us-east-1d skipping because this region is currently not supported
2020/01/25 17:32:07 region.go:280: us-east-1 Instance data missing for m5n.2xlarge in us-east-1a skipping because this region is currently not supported
2020/01/25 17:32:07 region.go:280: us-east-1 Instance data missing for g4dn.12xlarge in us-east-1a skipping because this region is currently not supported
2020/01/25 17:32:07 region.go:280: us-east-1 Instance data missing for m5n.12xlarge in us-east-1d skipping because this region is currently not supported
2020/01/25 17:32:07 region.go:280: us-east-1 Instance data missing for r5n.2xlarge in us-east-1a skipping because this region is currently not supported
2020/01/25 17:32:07 region.go:280: us-east-1 Instance data missing for m5n.4xlarge in us-east-1b skipping because this region is currently not supported
2020/01/25 17:32:07 region.go:280: us-east-1 Instance data missing for c5d.24xlarge in us-east-1a skipping because this region is currently not supported
2020/01/25 17:32:07 region.go:280: us-east-1 Instance data missing for r5n.2xlarge in us-east-1c skipping because this region is currently not supported
2020/01/25 17:32:07 region.go:280: us-east-1 Instance data missing for r5n.8xlarge in us-east-1b skipping because this region is currently not supported
2020/01/25 17:32:07 region.go:280: us-east-1 Instance data missing for r5n.8xlarge in us-east-1f skipping because this region is currently not supported
2020/01/25 17:32:07 region.go:280: us-east-1 Instance data missing for r5n.8xlarge in us-east-1a skipping because this region is currently not supported
2020/01/25 17:32:07 region.go:280: us-east-1 Instance data missing for r5n.8xlarge in us-east-1d skipping because this region is currently not supported
2020/01/25 17:32:07 region.go:280: us-east-1 Instance data missing for r5n.8xlarge in us-east-1c skipping because this region is currently not supported
2020/01/25 17:32:07 region.go:280: us-east-1 Instance data missing for m5dn.xlarge in us-east-1b skipping because this region is currently not supported
2020/01/25 17:32:07 region.go:280: us-east-1 Instance data missing for r5dn.8xlarge in us-east-1b skipping because this region is currently not supported
2020/01/25 17:32:07 region.go:280: us-east-1 Instance data missing for r5dn.8xlarge in us-east-1f skipping because this region is currently not supported
2020/01/25 17:32:07 region.go:280: us-east-1 Instance data missing for r5dn.8xlarge in us-east-1a skipping because this region is currently not supported
2020/01/25 17:32:07 region.go:280: us-east-1 Instance data missing for r5dn.8xlarge in us-east-1d skipping because this region is currently not supported
2020/01/25 17:32:07 region.go:280: us-east-1 Instance data missing for r5dn.8xlarge in us-east-1c skipping because this region is currently not supported
2020/01/25 17:32:07 region.go:280: us-east-1 Instance data missing for m5dn.xlarge in us-east-1c skipping because this region is currently not supported
2020/01/25 17:32:07 region.go:280: us-east-1 Instance data missing for m5n.12xlarge in us-east-1a skipping because this region is currently not supported
2020/01/25 17:32:07 region.go:280: us-east-1 Instance data missing for g4dn.2xlarge in us-east-1b skipping because this region is currently not supported
2020/01/25 17:32:07 region.go:280: us-east-1 Instance data missing for m5n.4xlarge in us-east-1a skipping because this region is currently not supported
2020/01/25 17:32:07 region.go:280: us-east-1 Instance data missing for g4dn.xlarge in us-east-1c skipping because this region is currently not supported
2020/01/25 17:32:07 region.go:280: us-east-1 Instance data missing for r5dn.xlarge in us-east-1f skipping because this region is currently not supported
2020/01/25 17:32:07 region.go:280: us-east-1 Instance data missing for c5d.12xlarge in us-east-1b skipping because this region is currently not supported
2020/01/25 17:32:07 region.go:280: us-east-1 Instance data missing for m5dn.2xlarge in us-east-1f skipping because this region is currently not supported
2020/01/25 17:32:07 region.go:280: us-east-1 Instance data missing for m5dn.2xlarge in us-east-1a skipping because this region is currently not supported
2020/01/25 17:32:07 region.go:280: us-east-1 Instance data missing for m5dn.2xlarge in us-east-1c skipping because this region is currently not supported
2020/01/25 17:32:07 region.go:280: us-east-1 Instance data missing for r5dn.xlarge in us-east-1d skipping because this region is currently not supported
2020/01/25 17:32:07 region.go:280: us-east-1 Instance data missing for r5n.xlarge in us-east-1c skipping because this region is currently not supported
2020/01/25 17:32:07 region.go:280: us-east-1 Instance data missing for g4dn.4xlarge in us-east-1b skipping because this region is currently not supported
2020/01/25 17:32:07 region.go:280: us-east-1 Instance data missing for c5d.metal in us-east-1a skipping because this region is currently not supported
2020/01/25 17:32:07 region.go:280: us-east-1 Instance data missing for m5n.8xlarge in us-east-1b skipping because this region is currently not supported
2020/01/25 17:32:07 region.go:280: us-east-1 Instance data missing for m5n.8xlarge in us-east-1f skipping because this region is currently not supported
2020/01/25 17:32:07 region.go:280: us-east-1 Instance data missing for m5n.8xlarge in us-east-1a skipping because this region is currently not supported
2020/01/25 17:32:07 region.go:280: us-east-1 Instance data missing for m5n.8xlarge in us-east-1d skipping because this region is currently not supported
2020/01/25 17:32:07 region.go:280: us-east-1 Instance data missing for m5n.8xlarge in us-east-1c skipping because this region is currently not supported
2020/01/25 17:32:07 region.go:280: us-east-1 Instance data missing for r5n.xlarge in us-east-1b skipping because this region is currently not supported
2020/01/25 17:32:07 region.go:280: us-east-1 Instance data missing for m5dn.2xlarge in us-east-1b skipping because this region is currently not supported
2020/01/25 17:32:07 region.go:280: us-east-1 Instance data missing for inf1.24xlarge in us-east-1b skipping because this region is currently not supported
2020/01/25 17:32:07 region.go:280: us-east-1 Instance data missing for inf1.24xlarge in us-east-1f skipping because this region is currently not supported
2020/01/25 17:32:07 region.go:280: us-east-1 Instance data missing for inf1.24xlarge in us-east-1d skipping because this region is currently not supported
2020/01/25 17:32:07 region.go:280: us-east-1 Instance data missing for c5d.12xlarge in us-east-1d skipping because this region is currently not supported
2020/01/25 17:32:07 region.go:280: us-east-1 Instance data missing for g4dn.2xlarge in us-east-1d skipping because this region is currently not supported
2020/01/25 17:32:07 region.go:280: us-east-1 Instance data missing for r5dn.xlarge in us-east-1a skipping because this region is currently not supported
2020/01/25 17:32:07 region.go:280: us-east-1 Instance data missing for g4dn.2xlarge in us-east-1a skipping because this region is currently not supported
2020/01/25 17:32:07 region.go:280: us-east-1 Instance data missing for r5dn.2xlarge in us-east-1f skipping because this region is currently not supported
2020/01/25 17:32:07 region.go:280: us-east-1 Instance data missing for r5dn.2xlarge in us-east-1d skipping because this region is currently not supported
2020/01/25 17:32:07 region.go:280: us-east-1 Instance data missing for g4dn.xlarge in us-east-1f skipping because this region is currently not supported
2020/01/25 17:32:07 region.go:280: us-east-1 Instance data missing for g4dn.xlarge in us-east-1b skipping because this region is currently not supported
2020/01/25 17:32:07 region.go:280: us-east-1 Instance data missing for r5dn.2xlarge in us-east-1b skipping because this region is currently not supported
2020/01/25 17:32:07 region.go:280: us-east-1 Instance data missing for r5dn.large in us-east-1b skipping because this region is currently not supported
2020/01/25 17:32:07 region.go:280: us-east-1 Instance data missing for r5dn.large in us-east-1f skipping because this region is currently not supported
2020/01/25 17:32:07 region.go:280: us-east-1 Instance data missing for r5dn.large in us-east-1a skipping because this region is currently not supported
2020/01/25 17:32:07 region.go:280: us-east-1 Instance data missing for r5dn.large in us-east-1d skipping because this region is currently not supported
2020/01/25 17:32:07 region.go:280: us-east-1 Instance data missing for r5dn.large in us-east-1c skipping because this region is currently not supported
2020/01/25 17:32:07 region.go:280: us-east-1 Instance data missing for r5dn.4xlarge in us-east-1d skipping because this region is currently not supported
2020/01/25 17:32:07 region.go:280: us-east-1 Instance data missing for g4dn.xlarge in us-east-1d skipping because this region is currently not supported
2020/01/25 17:32:07 region.go:280: us-east-1 Instance data missing for m5dn.2xlarge in us-east-1d skipping because this region is currently not supported
2020/01/25 17:32:07 region.go:280: us-east-1 Instance data missing for inf1.xlarge in us-east-1f skipping because this region is currently not supported
2020/01/25 17:32:07 region.go:280: us-east-1 Instance data missing for inf1.xlarge in us-east-1d skipping because this region is currently not supported
2020/01/25 17:32:07 region.go:280: us-east-1 Instance data missing for r5n.large in us-east-1b skipping because this region is currently not supported
2020/01/25 17:32:07 region.go:280: us-east-1 Instance data missing for r5n.large in us-east-1f skipping because this region is currently not supported
2020/01/25 17:32:07 region.go:280: us-east-1 Instance data missing for r5n.large in us-east-1a skipping because this region is currently not supported
2020/01/25 17:32:07 region.go:280: us-east-1 Instance data missing for r5n.large in us-east-1d skipping because this region is currently not supported
2020/01/25 17:32:07 region.go:280: us-east-1 Instance data missing for r5n.large in us-east-1c skipping because this region is currently not supported
2020/01/25 17:32:07 region.go:280: us-east-1 Instance data missing for r5dn.xlarge in us-east-1b skipping because this region is currently not supported
2020/01/25 17:32:07 region.go:280: us-east-1 Instance data missing for m5dn.8xlarge in us-east-1d skipping because this region is currently not supported
2020/01/25 17:32:07 region.go:280: us-east-1 Instance data missing for c5d.24xlarge in us-east-1b skipping because this region is currently not supported
2020/01/25 17:32:07 region.go:280: us-east-1 Instance data missing for m5dn.4xlarge in us-east-1b skipping because this region is currently not supported
2020/01/25 17:32:07 region.go:280: us-east-1 Instance data missing for m5dn.4xlarge in us-east-1f skipping because this region is currently not supported
2020/01/25 17:32:07 region.go:280: us-east-1 Instance data missing for m5dn.4xlarge in us-east-1a skipping because this region is currently not supported
2020/01/25 17:32:07 region.go:280: us-east-1 Instance data missing for m5dn.4xlarge in us-east-1d skipping because this region is currently not supported
2020/01/25 17:32:07 region.go:280: us-east-1 Instance data missing for m5dn.4xlarge in us-east-1c skipping because this region is currently not supported
2020/01/25 17:32:07 region.go:280: us-east-1 Instance data missing for m5dn.large in us-east-1b skipping because this region is currently not supported
2020/01/25 17:32:07 region.go:280: us-east-1 Instance data missing for m5dn.large in us-east-1f skipping because this region is currently not supported
2020/01/25 17:32:07 region.go:280: us-east-1 Instance data missing for m5dn.large in us-east-1a skipping because this region is currently not supported
2020/01/25 17:32:07 region.go:280: us-east-1 Instance data missing for m5dn.large in us-east-1d skipping because this region is currently not supported
2020/01/25 17:32:07 region.go:280: us-east-1 Instance data missing for m5dn.large in us-east-1c skipping because this region is currently not supported
2020/01/25 17:32:07 region.go:280: us-east-1 Instance data missing for r5n.12xlarge in us-east-1b skipping because this region is currently not supported
2020/01/25 17:32:07 region.go:280: us-east-1 Instance data missing for r5n.12xlarge in us-east-1f skipping because this region is currently not supported
2020/01/25 17:32:07 region.go:280: us-east-1 Instance data missing for r5n.12xlarge in us-east-1a skipping because this region is currently not supported
2020/01/25 17:32:07 region.go:280: us-east-1 Instance data missing for r5n.12xlarge in us-east-1d skipping because this region is currently not supported
2020/01/25 17:32:07 region.go:280: us-east-1 Instance data missing for r5n.12xlarge in us-east-1c skipping because this region is currently not supported
2020/01/25 17:32:07 region.go:280: us-east-1 Instance data missing for m5dn.8xlarge in us-east-1b skipping because this region is currently not supported
2020/01/25 17:32:07 region.go:280: us-east-1 Instance data missing for m5dn.8xlarge in us-east-1f skipping because this region is currently not supported
2020/01/25 17:32:07 region.go:280: us-east-1 Instance data missing for m5dn.8xlarge in us-east-1a skipping because this region is currently not supported
2020/01/25 17:32:07 region.go:280: us-east-1 Instance data missing for m5dn.8xlarge in us-east-1c skipping because this region is currently not supported
2020/01/25 17:32:07 region.go:280: us-east-1 Instance data missing for r5dn.12xlarge in us-east-1a skipping because this region is currently not supported
2020/01/25 17:32:07 region.go:280: us-east-1 Instance data missing for a1.metal in us-east-1b skipping because this region is currently not supported
2020/01/25 17:32:07 region.go:280: us-east-1 Instance data missing for a1.metal in us-east-1d skipping because this region is currently not supported
2020/01/25 17:32:07 region.go:280: us-east-1 Instance data missing for g4dn.2xlarge in us-east-1c skipping because this region is currently not supported
2020/01/25 17:32:07 region.go:280: us-east-1 Instance data missing for r5n.xlarge in us-east-1a skipping because this region is currently not supported
2020/01/25 17:32:07 region.go:280: us-east-1 Instance data missing for c5d.metal in us-east-1d skipping because this region is currently not supported
2020/01/25 17:32:07 region.go:280: us-east-1 Instance data missing for r5dn.12xlarge in us-east-1b skipping because this region is currently not supported
2020/01/25 17:32:07 region.go:280: us-east-1 Instance data missing for r5dn.xlarge in us-east-1c skipping because this region is currently not supported
2020/01/25 17:32:07 region.go:280: us-east-1 Instance data missing for c5d.12xlarge in us-east-1a skipping because this region is currently not supported
2020/01/25 17:32:07 region.go:280: us-east-1 Instance data missing for m5n.xlarge in us-east-1b skipping because this region is currently not supported
2020/01/25 17:32:07 region.go:280: us-east-1 Instance data missing for r5dn.2xlarge in us-east-1c skipping because this region is currently not supported
2020/01/25 17:32:07 region.go:280: us-east-1 Instance data missing for g4dn.8xlarge in us-east-1d skipping because this region is currently not supported
2020/01/25 17:32:07 region.go:280: us-east-1 Instance data missing for m5n.2xlarge in us-east-1b skipping because this region is currently not supported
2020/01/25 17:32:07 region.go:280: us-east-1 Instance data missing for r5dn.16xlarge in us-east-1b skipping because this region is currently not supported
2020/01/25 17:32:07 region.go:280: us-east-1 Instance data missing for r5dn.16xlarge in us-east-1f skipping because this region is currently not supported
2020/01/25 17:32:07 region.go:280: us-east-1 Instance data missing for r5dn.16xlarge in us-east-1a skipping because this region is currently not supported
2020/01/25 17:32:07 region.go:280: us-east-1 Instance data missing for r5dn.16xlarge in us-east-1d skipping because this region is currently not supported
2020/01/25 17:32:07 region.go:280: us-east-1 Instance data missing for r5n.2xlarge in us-east-1b skipping because this region is currently not supported
2020/01/25 17:32:07 region.go:280: us-east-1 Instance data missing for c5d.24xlarge in us-east-1d skipping because this region is currently not supported
2020/01/25 17:32:07 region.go:280: us-east-1 Instance data missing for m5n.4xlarge in us-east-1f skipping because this region is currently not supported
2020/01/25 17:32:07 region.go:280: us-east-1 Instance data missing for m5n.4xlarge in us-east-1c skipping because this region is currently not supported
2020/01/25 17:32:07 region.go:280: us-east-1 Instance data missing for g4dn.12xlarge in us-east-1b skipping because this region is currently not supported
2020/01/25 17:32:07 region.go:280: us-east-1 Instance data missing for g4dn.12xlarge in us-east-1f skipping because this region is currently not supported
2020/01/25 17:32:07 region.go:280: us-east-1 Instance data missing for g4dn.12xlarge in us-east-1d skipping because this region is currently not supported
2020/01/25 17:32:07 region.go:280: us-east-1 Instance data missing for g4dn.12xlarge in us-east-1c skipping because this region is currently not supported
2020/01/25 17:32:07 region.go:280: us-east-1 Instance data missing for m5dn.12xlarge in us-east-1b skipping because this region is currently not supported
2020/01/25 17:32:07 region.go:280: us-east-1 Instance data missing for m5dn.12xlarge in us-east-1f skipping because this region is currently not supported
2020/01/25 17:32:07 region.go:280: us-east-1 Instance data missing for m5dn.12xlarge in us-east-1a skipping because this region is currently not supported
2020/01/25 17:32:07 region.go:280: us-east-1 Instance data missing for m5dn.12xlarge in us-east-1d skipping because this region is currently not supported
2020/01/25 17:32:07 region.go:280: us-east-1 Instance data missing for m5dn.12xlarge in us-east-1c skipping because this region is currently not supported
2020/01/25 17:32:07 region.go:280: us-east-1 Instance data missing for r5n.24xlarge in us-east-1b skipping because this region is currently not supported
2020/01/25 17:32:07 region.go:280: us-east-1 Instance data missing for r5n.24xlarge in us-east-1f skipping because this region is currently not supported
2020/01/25 17:32:07 region.go:280: us-east-1 Instance data missing for r5n.24xlarge in us-east-1a skipping because this region is currently not supported
2020/01/25 17:32:07 region.go:280: us-east-1 Instance data missing for r5n.24xlarge in us-east-1d skipping because this region is currently not supported
2020/01/25 17:32:07 region.go:280: us-east-1 Instance data missing for r5n.24xlarge in us-east-1c skipping because this region is currently not supported
2020/01/25 17:32:07 region.go:280: us-east-1 Instance data missing for r5dn.12xlarge in us-east-1f skipping because this region is currently not supported
2020/01/25 17:32:07 region.go:280: us-east-1 Instance data missing for r5dn.12xlarge in us-east-1d skipping because this region is currently not supported
2020/01/25 17:32:07 region.go:280: us-east-1 Instance data missing for r5dn.12xlarge in us-east-1c skipping because this region is currently not supported
2020/01/25 17:32:07 region.go:280: us-east-1 Instance data missing for m5n.xlarge in us-east-1a skipping because this region is currently not supported
2020/01/25 17:32:07 region.go:280: us-east-1 Instance data missing for g4dn.4xlarge in us-east-1d skipping because this region is currently not supported
2020/01/25 17:32:07 region.go:280: us-east-1 Instance data missing for r5dn.2xlarge in us-east-1a skipping because this region is currently not supported
2020/01/25 17:32:07 region.go:280: us-east-1 Instance data missing for r5n.4xlarge in us-east-1b skipping because this region is currently not supported
2020/01/25 17:32:07 region.go:280: us-east-1 Instance data missing for m5n.12xlarge in us-east-1b skipping because this region is currently not supported
2020/01/25 17:32:07 region.go:280: us-east-1 Instance data missing for m5n.12xlarge in us-east-1f skipping because this region is currently not supported
2020/01/25 17:32:07 region.go:280: us-east-1 Instance data missing for m5n.12xlarge in us-east-1c skipping because this region is currently not supported
2020/01/25 17:32:07 region.go:280: us-east-1 Instance data missing for m5n.16xlarge in us-east-1b skipping because this region is currently not supported
2020/01/25 17:32:07 region.go:280: us-east-1 Instance data missing for m5n.16xlarge in us-east-1f skipping because this region is currently not supported
2020/01/25 17:32:07 region.go:280: us-east-1 Instance data missing for m5n.16xlarge in us-east-1a skipping because this region is currently not supported
2020/01/25 17:32:07 region.go:280: us-east-1 Instance data missing for m5n.16xlarge in us-east-1d skipping because this region is currently not supported
2020/01/25 17:32:07 region.go:280: us-east-1 Instance data missing for m5n.16xlarge in us-east-1c skipping because this region is currently not supported
2020/01/25 17:32:07 region.go:280: us-east-1 Instance data missing for r5dn.4xlarge in us-east-1b skipping because this region is currently not supported
2020/01/25 17:32:07 region.go:280: us-east-1 Instance data missing for r5dn.4xlarge in us-east-1f skipping because this region is currently not supported
2020/01/25 17:32:07 region.go:280: us-east-1 Instance data missing for r5dn.4xlarge in us-east-1a skipping because this region is currently not supported
2020/01/25 17:32:07 region.go:280: us-east-1 Instance data missing for r5dn.4xlarge in us-east-1c skipping because this region is currently not supported
2020/01/25 17:32:07 region.go:280: us-east-1 Instance data missing for r5n.xlarge in us-east-1d skipping because this region is currently not supported
2020/01/25 17:32:07 region.go:280: us-east-1 Instance data missing for m5n.xlarge in us-east-1d skipping because this region is currently not supported
2020/01/25 17:32:07 region.go:280: us-east-1 Instance data missing for g4dn.4xlarge in us-east-1a skipping because this region is currently not supported

```
