### PR TITLE
re #430: allows counting ephemeral volumes desired via AMI specified by ASG launch template (w/ version)

### LINKED ISSUE #430: autospotting not respecting presence of ephemeral volume in AMI/launch template
# Github issue #

## Issue type ##

- Bug Report

## Build number #

```
nightly-1137
```
believe we used master branch code from end of April 2020.

## Environment ##

- AWS region: us-east-1
- Type of environment: VPC

## Summary ##

I've got an ASG set up to launch instances from a Launch Template using m5d.xlarge instances. However autospotting is allowing spot instances without an ephemeral volume to be used.

I've attempted to detail my setup below, however if there's some config I've missed that makes the ephemeral volume requirement apparent to autospotting in a different way than I attempted please do let me know! :)

## Steps to reproduce ##

The AMI used for this template requests an ephemeral volume:
```
Block Devices
/dev/xvda=snap-0a74061116e945b70:16:true:gp2, /dev/sdb=ephemeral0
```

The launch template says: `Currently no volumes details are specified and therefore the instances launch with the template default volume settings`. When I go to modify the template I can only add EBS volumes, but the instance store volume is listed:

Screen Shot 2020-05-13 at 11 40 40 AM

Debug output from autospotting shows:
```
2020/05/13 12:54:43 instance.go:373: Comparing current type m5d.xlarge with price 0.226 with candidate m5.xlarge with price 0.0815
2020/05/13 12:54:43 instance.go:327: Checking allowed/disallowed list
2020/05/13 12:54:43 instance.go:219: Comparing class spot/instance:
2020/05/13 12:54:43 instance.go:220: 	Spot CPU/memory/GPU:  4  /  16  /  0
2020/05/13 12:54:43 instance.go:222: 	Instance CPU/memory/GPU:  4  /  16  /  0
2020/05/13 12:54:43 instance.go:286: Comparing storage spot/instance:
2020/05/13 12:54:43 instance.go:287: 	Spot volumes/size/ssd:  0 0 false <-----------
2020/05/13 12:54:43 instance.go:291: 	Instance volumes/size/ssd:  0 150 true <-----------
2020/05/13 12:54:43 instance.go:312: Comparing virtualization spot/instance:
2020/05/13 12:54:43 instance.go:313: 	Spot virtualization:  [HVM]
2020/05/13 12:54:43 instance.go:314: 	Instance virtualization:  hvm
2020/05/13 12:54:43 instance.go:383: 	MATCH FOUND, added m5.xlarge to launch candiates list
```

I took a quick look through the code and came upon:

```
	usedMappings := i.asg.launchConfiguration.countLaunchConfigEphemeralVolumes()
	attachedVolumesNumber := min(usedMappings, current.instanceStoreDeviceCount)
...
	i.isStorageCompatible(candidate, attachedVolumesNumber) &&
```

Stands to reason one of those terms is 0 and the min is going with that. I suspect it's usedMappings but not entirely sure.

## Expected results ##

Expecting launch template with AMI having ephemeral volume specified to require instance types that have an ephemeral volume available.

## Actual results ##

```text
```

### PR DESCRIPTION
**Pull request by karock**
# Issue Type

- Feature Pull Request

## Summary

Fixes #430, where ephemeral volumes weren't being counted from the AMI used by a launch template when considering the acceptable instance types.

## Code contribution checklist

1. [x] I hereby allow the Copyright holder the rights to distribute this piece of
   code under any software license.
1. [x] The contribution fixes a single existing github issue, and it is linked
   to it.
1. [x] The code is as simple as possible, readable and follows the idiomatic Go
  [guidelines](https://golang.org/doc/effective_go.html).
1. [x] All new functionality is covered by automated test cases so the overall
  test coverage doesn't decrease.
1. [x] No issues are reported when running `make full-test`.
1. [x] Functionality not applicable to all users should be configurable.
1. [x] Configurations should be exposed through Lambda function environment
   variables which are also passed as parameters to the
   [CloudFormation](https://github.com/cristim/autospotting/blob/master/cloudformation/stacks/AutoSpotting/template.yaml)
   and
   [Terraform](https://github.com/autospotting/terraform-aws-autospotting/main.tf)
   stacks defined as infrastructure code.
1. [x] Global configurations set from the infrastructure stack level should also
   support per-group overrides using tags.
1. [x] Tags names and expected values should be similar to the other existing
   configurations.
1. [x] Both global and tag-based configuration mechanisms should be tested and
  proven to work using log output from various test runs.
1. [x] The logs should be kept as clean as possible (use log levels as
  appropriate) and formatted consistently to the existing log output.
1. [x] The documentation is updated to cover the new behavior, as well as the
   new configuration options for both stack parameters and tag overrides.
1. [ ] A code reviewer reproduced the problem and can confirm the code
  contribution actually resolves it.

### CODE REVIEW

File: core/autoscaling.go [hunk 1]
```diff
@@ -62,6 +63,59 @@ func (a *autoScalingGroup) loadLaunchConfiguration() (*launchConfiguration, erro
...
+	}
+
+	resp, err := svc.DescribeLaunchTemplateVersions(params)
+
+	if err != nil {
+		logger.Println(err.Error())
+		return nil, err
+	}
+
+	ltv := resp.LaunchTemplateVersions[0]
```
Comment (cristim) [inline core/autoscaling.go:99]: I would have a check above in case the length of resp.LaunchTemplateVersions is zero

File: core/autoscaling.go [hunk 2]
```diff
@@ -62,6 +63,59 @@ func (a *autoScalingGroup) loadLaunchConfiguration() (*launchConfiguration, erro
...
+
+	params2 := &ec2.DescribeImagesInput{
+		ImageIds: []*string{ltv.LaunchTemplateData.ImageId},
+	}
+
+	resp2, err2 := svc.DescribeImages(params2)
+
+	if err2 != nil {
```
Comment (cristim) [inline core/autoscaling.go:107]: also add a condition here for the length of resp.Images, which below at line 114 we assume to be at least 1

File: core/autoscaling.go [hunk 3]
```diff
@@ -205,6 +259,7 @@ func (a *autoScalingGroup) cronEventAction() runer {
 		}
 
 		a.loadLaunchConfiguration()
+		a.loadLaunchTemplate()
```
Comment (cristim) [inline core/autoscaling.go:262]: why do we return anything on `a.loadLaunchTemplate` if we ignore both its return values?

File: core/instance.go [hunk 4]
```diff
@@ -917,3 +920,9 @@ func min(x, y int) int {
 	}
 	return y
 }
+func max(x, y int) int {
```
Comment (cristim) [inline core/instance.go:923]: do we need to define this again? I think we had it defined somewhere else.

Hopefully we'll soon get some sort of generics support in Go to avoid the need to define this sort of things.

File: core/autoscaling.go (hunk 3 above)
Comment (karock) [reply core/autoscaling.go:262]: I was using loadLaunchConfiguration as my template, looks like it has the same issue. In both cases only the tests use the return values. I can change it if you like though.

File: core/instance.go (hunk 4 above)
Comment (karock) [reply core/instance.go:923]: I only saw `min` defined in this way, right above where I added this change.

Comment (cristim) [reply core/instance.go:923]: Okay, thanks

File: core/autoscaling.go (hunk 1 above)
Comment (karock) [reply core/autoscaling.go:103]: addressed in https://github.com/AutoSpotting/AutoSpotting/pull/446/commits/c1153e58d76ad5d84dd1e5a30a0ddfaa823f26c0

File: core/autoscaling.go (hunk 2 above)
Comment (karock) [reply core/autoscaling.go:111]: addressed in https://github.com/AutoSpotting/AutoSpotting/pull/446/commits/c1153e58d76ad5d84dd1e5a30a0ddfaa823f26c0

**Comment by cristim** [comment]
thanks for your contribution @karock
